---
title: "国内外疫情态势对比分析"
author: "刘崟 慕慧君 肖雨婷 王洁 卢晋萍"
date: "2020年5月29日"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## 1 绪论


- 1.1 背景及意义

- 1.2 文献综述

- 1.3 主要内容及框架


## 1.1 背景及意义

&emsp;&emsp;2020年初，不明原因的病毒性肺炎在中国武汉市爆发，随后，其病原体被确定为新型冠状病毒，并在全球多个国家相继出现。根据世界卫生组织报告，时至2020年5月28日，美国累积确诊病例已经达到176万多例，巴西、俄罗斯、西班牙、英国、意大利、法国、德国、印度、土耳其、伊朗、秘鲁等10多个国家新冠肺炎累积确诊病例在10-50万例，而在疫情最早爆发的中国地区以及加拿大等其他100多个国家累积确诊病例均控制在10万例以下。

---

&emsp;&emsp;从以上数据可以看出，同一病毒性肺炎在不同国家呈现出不同的发展态势，且差异较大。研究疫情发展规律，掌握疫情的发展态势，有利于政府安抚民心以及科学有效地制定防控政策。疫情发展结果的差异，与各国具体的疫情防控政策有关，也与各国的文化及其他具体情况相关。本文对全球疫情的发展态势进行了可视化分析，从全局的角度了解各个国家疫情的发展动态，并结合各国具体因素，分析疫情结果差异的原因，探究疫情的发展规律，为一国科学做好疫情防控工作提供相关建议。

## 1.2 文献综述

[1]杨吉安,颜忠诚.基于生态模型的新型冠状病毒肺炎疫情分析[J/OL].首都师范大学学报(自然科学版):1-12[2020-05-21]

&emsp;&emsp;杨安吉，颜忠诚运用logistic模型对新冠肺炎的发展趋势进行了研究和解释，结果表明，logistic增长曲线的拟合值与实际观测数据差异较小，中国内地COVID-19疫情的累积确诊患者病例数、累积治愈患者例数和累计死亡患者例数变化趋势基本符合logistic增长曲线。可以看出logistic模型对疫情的发展趋势具有较好的拟合效果；

[2]易大莉,李高明,冷怀明.新型冠状病毒肺炎疫情发展区域差异的聚类分析[J/OL].重庆医科大学学报:1-6[2020-05-27]

&emsp;&emsp;易大莉等人使用聚类分析方法对新冠病毒肺炎疫情的发展进行区域差异分析；

---

[3]武文韬,柏如海,李达宁,冯敖梓,徐安定,吕军.广东省新型冠状病毒肺炎疫情流行趋势的初步预测[J].暨南大学学报(自然科学与医学版),2020,41(02):181-185.

&emsp;&emsp;武文韬等人运用SIR模型，通过计算和预测广东省新型冠状病毒肺炎的基本再生数,研究广东省疫情的流行趋势为其防控和相关政策支持提供依据；

[4]杨雨琦,孙琦,王悦欣,严雪凌,乐涛.重庆市新型冠状病毒肺炎(NCP)疫情分析与趋势预测[J].重庆师范大学学报(自然科学版),2020,37(01):135-140.

&emsp;&emsp;杨宇琦等人使用官方数据,计算出此次疫情确诊病例环比增长率、治愈率和死亡率,绘制变化曲线图分析疫情发展态势，并建立SIR传染病模型进行趋势预测；

---

[5]张荣强,刘辉,李凤英,李向文,刘启玲,李星慧,孙娜,张蓓,史传道.全球2019冠状病毒病（COVID-19）与甲型流感（2009-H1N1）疫情初期的流行病学对比分析及中医药防治策略研究[J/OL].陕西中医药大学学报:1-7[2020-05-29].

&emsp;&emsp;张荣强等人采用Excel、Origin软件开展H1N1和COVID-19的描述性流行病学分析，并分析二者的变化规律，探讨和比较2019冠状病毒病（COVID-19）和甲型流感（2009-H1N1）疫情初期的变化趋势及流行特征；

《Generalized logistic growth modeling of the COVID-19 outbreak in 29 provinces in China and in the rest of the world》 一文将logistic增长模型、广义logistic 增长模型 、广义增长模型和广义Richards模型与1月19日至3月10日全国、29个省、4个重灾区和整个欧洲的报告感染病例数进行了校正。不同的模型提供了各个场景预测的上下限。

---

&emsp;&emsp;以上文献多是关于局部地区的新冠肺炎疫情发展趋势的分析，方法上多用到SIR模型以及logistic增长模型，而关于全球性的疫情态势分析极少。本文着眼全球疫情角度，对国内外疫情发展态势进行分析，从多角度对全球疫情发展态势进行刻画，由于分析的国家地区较多，使用SIR模型需要考虑的额外因素较多，因此本文在进行趋势拟合和预测时采用了logistic增长模型进行分析，并根据所得的结论为抵制新冠病毒肺炎疫情提供相关建议。

## 1.3 论文框架及主要内容


- 1.基于全球疫情态势的描述性统计分析

- 2.聚类分析

- 3.趋势拟合及预测

- 4.总结及建议

